version: '3.8'

services:
  todo-minimal-api:
    image: postgres:17
    container_name: todo-minimal-db
    restart: 'no'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_LOGGING: jsonlog
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      - ./logs:/var/log/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - todo-minimal-net

networks:
  todo-minimal-net:
    driver: bridge

volumes:
  postgres_data:
